plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'com.modrinth.minotaur' version '2.+'
}

version = project.mod_version
group = project.maven_group
base.archivesName = project.archives_base_name

repositories {
    mavenCentral()
}

loom {
    splitEnvironmentSourceSets()

    mods {
        faststonecutter {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

def modVersion = project.version

processResources {
    inputs.property 'version', modVersion

    filesMatching('fabric.mod.json') {
        expand 'version': modVersion
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

test {
    useJUnitPlatform()
}

def archiveName = base.archivesName.get()

jar {
    inputs.property 'archiveName', archiveName

    from('LICENSE') {
        rename { "${it}_${archiveName}" }
    }
}

modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    projectId = "faststonecutter"
    versionNumber = project.mod_version
    versionType = "release"
    uploadFile = tasks.named("jar")
    gameVersions = ["26.1", "26.2"]
    loaders = ["fabric"]
    changelog = file("CHANGELOG.md").exists() ? file("CHANGELOG.md").text : ""
}
