org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.1.2
loader_version=0.19.5
loom_version=1.17.19
fabric_version=0.155.3+26.1.2
modrinth_game_versions=26.1,26.1.1,26.1.2

mod_version=1.0.2
maven_group=net.deanxbox
archives_base_name=faststonecutter
